name: Java CI with Gradle
on:
  push:
    branches:
      - master
jobs:
  e2e-tests:
    runs-on: windows-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          architecture: 'x64'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies and run tests
        run: npm install && npm test