name: Java CI with Gradle [UBUNTU] Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Java version "17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Node version "20"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Allure
        run: npm install -g allure-commandline

  install_dependencies:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libhyphen0 libmanette-0.2-0 libflite1 libgles2 libwoff1 libvpx7 gstreamer1.0-libav

  install_gradle:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - name: Download and extract Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-7.3-bin.zip
          unzip -q gradle-7.3-bin.zip
      - name: Build with Gradle
        run: <path-to-build.gradle>/gradle-7.3/bin/gradle build -x test --no-build-cache

  install_playwright:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - name: Uninstall old Debug
        run: npm uninstall debug
      - name: Install Debug "4.3.1"
        run: npm install debug@4.3.1
      - name: Install Playwright version "1.42.0"
        run: npm install playwright@1.42.0
      - name: Install Playwright browsers
        run: npx playwright install chrome

  run_tests:
    needs: [install_gradle, install_playwright, install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: List Directories before tests
        run: ls -R
      - name: ~~~~~~~ Run tests ~~~~~~~
        run: xvfb-run --auto-servernum --server-args="-screen 0 2000x1000x24" ./gradle-7.3/bin/gradle test
      - name: List Directories after tests
        run: ls -R

  archive_failed_tests:
    needs: run_tests
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Archive [Allure attachments for failed tests]
        uses: actions/upload-artifact@v4
        with:
          name: allure-attachments for failed tests
          path: |
            src/test_logs/*

  publish_allure_report:
    needs: run_tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Build allure report on gh-pages
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history