name: Java CI with Gradle (Ubuntu) - Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Java version "17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check Java version
        run: java -version

      - name: Check JVM version
        run: echo $JAVA_HOME

      - name: Check Java Core version
        run: javac -version

      - name: Install Node version "20"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check Node version
        run: node --version

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - uses: actions/checkout@v4

      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libhyphen0 libmanette-0.2-0 libflite1 libgles2 libwoff1 libvpx7 gstreamer1.0-libav

      - name: Uninstall old Debug (optional)
        run: npm uninstall debug

      - name: Install Debug "4.3.1" (optional)
        run: npm install debug@4.3.1  # Update version as needed

      - name: Check Debug version (optional)
        run: npm list debug

  install-playwright:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Install Playwright version "1.42.0"
        run: npm install playwright@1.42.0  # Update version as needed

      - name: Check Playwright version
        run: npx playwright --version

      - name: Install Playwright browsers
        run: npx playwright install chrome

      - name: Check installed Playwright browsers versions
        run: npx playwright --version

  install-allure:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Check Allure version
        run: allure --version

  run-tests:
    runs-on: ubuntu-latest
    needs: [ setup-environment, install-dependencies, install-playwright, install-allure ]
    steps:
      - uses: actions/checkout@v4

      - name: List Directories before tests (optional)
        if: always()
        run: ls -R
      - name: Set execute permission for gradlew
        run: chmod +x gradlew

      - name: ~~~~~~~ Run tests ~~~~~~~

        run: xvfb-run --auto-servernum --server-args="-screen 0 2000x1000x24" ./gradlew test

      - name: List Directories after tests (optional)
        if: always()
        run: ls -R

  archive-results:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4

      - name: Archive [test results]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gradle-results
          path: |
            build/reports/tests/test/*

      - name: Archive [Allure attachments for failed tests]
        uses: actions/upload-artifact@v4
        if: always()  # Consider using failure-only strategy for efficiency
        with:
          name: allure-attachments
          path: ''
