name: Java CI with Gradle Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      # Установка прав доступа к gradlew
      - name: Set execute permission for gradlew
        run: git update-index --chmod=+x gradlew

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: List Directory Contents
        run: Get-ChildItem -Recurse
      - name: Build & Install
        run: .\gradlew build -x test --no-build-cache
      - name: Install Playwright
        run: .\gradlew playwrightInstall
      - name: Run tests
        run: .\gradlew test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: |
            build/reports/tests/test/*