name: Java CI with Gradle [UBUNTU] Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Java version "17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java version
        run: java -version
      - name: Check JVM version
        run: echo $JAVA_HOME
      - name: Check Java Core version
        run: javac -version

  install_dependencies:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0 libhyphen0 libmanette-0.2-0 libflite1 libgles2 libwoff1 libvpx7 gstreamer1.0-libav
      - name: Uninstall old Debug
        run: npm uninstall debug
      - name: Install Debug "4.3.1"
        run: npm install debug@4.3.1
      - name: Check Debug version
        run: npm list debug

  install_gradle:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew build -x test --no-build-cache
      - name: Check Gradle version
        run: ./gradlew --version
      - name: Clean Gradle build
        run: ./gradlew clean

  install_playwright:
    needs: install_gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Playwright version "1.42.0"
        run: npm install playwright@1.42.0
      - name: Check Playwright version
        run: npx playwright --version
      - name: Install Playwright browsers
        run: npx playwright install chrome
      - name: Check installed Playwright browsers versions
        run: npx playwright --version

  install_allure:
    needs: install_playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Check Allure version
        run: allure --version

  run_tests:
    needs: install_allure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List Directories before tests
        if: always()
        run: ls -R
      - name: ~~~~~~~ Run tests ~~~~~~~
        run: xvfb-run --auto-servernum --server-args="-screen 0 2000x1000x24" ./gradlew test
      - name: List Directories after tests
        if: always()
        run: ls -R

  archive_failed_tests:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive [Allure attachments for failed tests]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-attachments for failed tests
          path: |
            src/test_logs/*

  publish_report:
    needs: archive_failed_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build allure report on gh-pages
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history