name: Java CI with Gradle [UBUNTU] Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #// !  Установка Java
      - name: Set execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Java version "21"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      #// !  Проверка версий Java, JVM, Java Core
      - name: Check Java version
        run: java -version
      - name: Check JVM version
        run: echo $JAVA_HOME
      - name: Check Java Core version
        run: javac -version
      #// !  Установка Node.js
      - name: Install Node version "19"
        uses: actions/setup-node@v4
        with:
          node-version: '19'
      - name: Check Node version
        run: node --version
      #// !  Установка Gradle
      - name: Install Gradle version "8.6"
        run: ./gradlew build -x test --no-build-cache
      - name: Check Gradle version
        run: ./gradlew --version
      - name: Clean Gradle build
        run: ./gradlew clean
      #// !  Установка Playwright
      - name: Install Playwright version "1.42.0"
        run: npm install playwright@1.42.0
      - name: Check Playwright version
        run: npx playwright --version
      #// !  Установка Allure
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Check Allure version
        run: allure --version
      #// !  Список папок до тестов
      - name: List Directories before tests
        run:  Get-ChildItem -Recurse #ls -R
      #// !  Запуск тестов
      - name: ~~~~~~~ Run tests ~~~~~~~
        run: xvfb-run --auto-servernum --server-args="-screen 0 2000x1000x24" ./gradlew test
      #// !  Список папок после тестов
      - name: List Directories after tests
        run: Get-ChildItem -Recurse #ls -R
      #// ! Создание отчетоа Playwright
      - name: Archive [test results]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: |
            build/reports/tests/test/*
      #// !  Создание архива с файлами упавших тестов
      - name: Archive [Allure attachments for failed tests]
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-attachments for failed tests
          path: |
            src/test_logs/*
      #// !  Build test report
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      #  Publish test report
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3 # обновлено до v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history