name: Java CI with Gradle
on:
  push:
    branches:
      - master
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v3.8.2
        with:
          node-version: '20.11.1'
      - name: Set up JDK 21
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - uses: microsoft/playwright-github-action@v1

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: ./gradlew test

      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: |
            build/reports/tests/test/*