name: Java CI with Gradle Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build & Install
        working-directory: /src/main/java
        run: mvn -B install -DskipTests --no-transfer-progress
      - name: Install Playwright
        working-directory: /src/main/java
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"
      - name: Run tests
        working-directory: /src/main/java
        run: mvn test
      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: |
            build/reports/tests/test/*