name: Java CI with Gradle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: xvfb-run --auto-servernum -- ./gradlew build

      - name: Test with Gradle
        run: xvfb-run --auto-servernum -- ./gradlew test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-results
          path: build/reports/tests/
          retention-days: 30